name = "gmencz-faunadb"
type = "javascript"
account_id = "930ee94c5320c477a77b76445444be44"
workers_dev = true

[build]
command = "npm run build"
[build.upload]
format = "modules"
main = "./worker.mjs"

[durable_objects]
bindings = []